version: "3"
services:
  hmpps-person-on-probation-user-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-person-on-probation-user-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://person-on-probation-user-db:5432/person-on-probation-user?sslmode=prefer
      - SPRING_FLYWAY_URL=jdbc:postgresql://person-on-probation-user-db:5432/person-on-probation-user?sslmode=prefer

networks:
  hmpps:
