version: "3"
services:
  person-on-probation-user-db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hmpps
    container_name: person-on-probation-user-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=person-on-probation-user
      - POSTGRES_USER=person-on-probation-user
      - POSTGRES_DB=person-on-probation-user


networks:
  hmpps:

volumes:
  pgdata:
