server:
  shutdown: immediate

# Base URLs of downstream APIs. Switch the comments to use the real dev services instead of the test stubs
api:
  base:
    url:
      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      resettlementpassport: https://resettlement-passport-api-dev.hmpps.service.justice.gov.uk

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0
spring:
  devtools:
    add-properties: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: 'jdbc:postgresql://localhost:5432/person-on-probation-user?sslmode=prefer'
    username: person-on-probation-user
    password: person-on-probation-user
    hikari:
      pool-name: Person-On-Probation-User
      connectionTimeout: 1000
      validationTimeout: 500

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/person-on-probation-user?sslmode=prefer
    user: person-on-probation-user
    password: person-on-probation-user

  feature-toggles:
    afine: true