generic-service:
  nameOverride: hmpps-person-on-probation-user-api
  productId: "" # productId for the product that this belongs too, i.e. DPS001, see README.md for details
  resources:
    requests:
      cpu: 250m
    limits:
      cpu: 500m

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-person-on-probation-user-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: person-on-probation-user-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-person-on-probation-user-api:
      PERSON_ON_PROBATION_API_CLIENT_ID: "SYSTEM_CLIENT_ID"
      PERSON_ON_PROBATION_API_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    hmpps-template-kotlin-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-postgresql-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"

  allowlist:
    groups:
      - internal

custommetrics:
  enabled: true
  scrapeInterval: 15s
  metricsPath: /prometheus
  metricsPort: http

generic-prometheus-alerts:
  targetApplication: hmpps-resettlement-passport-api
