apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hmpps-person-on-probation-user-api
  namespace: hmpps-person-on-probation-user-service-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hmpps-person-on-probation-user-api
  minReplicas: 4
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50