---
# Per environment values which override defaults in hmpps-person-on-probation-user-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: person-on-probation-user-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_RESETTLEMENTPASSPORT: https://resettlement-passport-api-preprod.hmpps.service.justice.gov.uk


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-person-on-probation-user-non-prod
